// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqx7-pPaCbPTorgoAHkWZ-cDdLotTfX_k',
    appId: '1:493355303911:web:45ea027783cfb6ececf342',
    messagingSenderId: '493355303911',
    projectId: 'erp-app-odcl',
    authDomain: 'erp-app-odcl.firebaseapp.com',
    storageBucket: 'erp-app-odcl.firebasestorage.app',
    measurementId: 'G-YGL70W4N8Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH-jGezHxq72V1w79P7GSz1Lu9OX9Kf4A',
    appId: '1:493355303911:android:4f17451746dd8a76ecf342',
    messagingSenderId: '493355303911',
    projectId: 'erp-app-odcl',
    storageBucket: 'erp-app-odcl.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP2vl94Oso77sSpExFR7Tu26D-WczGELg',
    appId: '1:493355303911:ios:1a948d7b8a03f5e7ecf342',
    messagingSenderId: '493355303911',
    projectId: 'erp-app-odcl',
    storageBucket: 'erp-app-odcl.firebasestorage.app',
    iosBundleId: 'com.example.erpDAnda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP2vl94Oso77sSpExFR7Tu26D-WczGELg',
    appId: '1:493355303911:ios:1a948d7b8a03f5e7ecf342',
    messagingSenderId: '493355303911',
    projectId: 'erp-app-odcl',
    storageBucket: 'erp-app-odcl.firebasestorage.app',
    iosBundleId: 'com.example.erpDAnda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqx7-pPaCbPTorgoAHkWZ-cDdLotTfX_k',
    appId: '1:493355303911:web:45c508f29fca2b95ecf342',
    messagingSenderId: '493355303911',
    projectId: 'erp-app-odcl',
    authDomain: 'erp-app-odcl.firebaseapp.com',
    storageBucket: 'erp-app-odcl.firebasestorage.app',
    measurementId: 'G-F8V5CS5ZQ0',
  );
}
